package Principal;

public class Main {
    public static void main() {

    String monedas = """
            1.	 ARS - Peso argentino (Argentina)
            2.	 AED - Dirham de los Emiratos Árabes Unidos (Emiratos Árabes Unidos)
            3.	 AFN - Afghani (Afganistán)
            4.	 ALL - Lek (Albania)
            5.	 AMD - Dram armenio (Armenia)
            6.	 ANG - Florín de las Antillas Neerlandesas (Antillas Neerlandesas)
            7.	 AOA - Kwanza (Angola)
            8.	 AUD - Dólar australiano (Australia)
            9.	 AWG - Florín arubeño (Aruba)
            10.	 AZN - Manat azerí (Azerbaiyán)
            11.	 BAM - Marco convertible (Bosnia y Herzegovina)
            12.	 BBD - Dólar de Barbados (Barbados)
            13.	 BDT - Taka (Bangladesh)
            14.	 BGN - Lev búlgaro (Bulgaria)
            15.	 BHD - Dinar bahreiní (Bahréin)
            16.	 BIF - Franco burundés (Burundi)
            17.	 BMD - Dólar bermudeño (Bermudas)
            18.	 BND - Dólar de Brunéi (Brunéi)
            19.	 BOB - Boliviano (Bolivia)
            20.	 BRL - Real brasileño (Brasil)
            21.	 BSD - Dólar bahameño (Bahamas)
            22.	 BTN - Ngultrum (Bután)
            23.	 BWP - Pula (Botsuana)
            24.	 BYN - Rublo bielorruso (Bielorrusia)
            25.	 BZD - Dólar beliceño (Belice)
            26.	 CAD - Dólar canadiense (Canadá)
            27.	 CDF - Franco congoleño (República Democrática del Congo)
            28.	 CHF - Franco suizo (Suiza)
            29.	 CLP - Peso chileno (Chile)
            30.	 CNY - Yuan (China)
            31.	 COP - Peso colombiano (Colombia)
            32.	 CRC - Colón costarricense (Costa Rica)
            33.	 CUP - Peso cubano (Cuba)
            34.	 CVE - Escudo caboverdiano (Cabo Verde)
            35.	 CZK - Corona checa (Chequia)
            36.	 DJF - Franco yibutiano (Yibuti)
            37.	 DKK - Corona danesa (Dinamarca)
            38.	 DOP - Peso dominicano (República Dominicana)
            39.	 DZD - Dinar argelino (Argelia)
            40.	 EGP - Libra egipcia (Egipto)
            41.	 ERN - Nakfa (Eritrea)
            42.	 ETB - Birr etíope (Etiopía)
            43.	 EUR - Euro (Unión Europea)
            44.	 FJD - Dólar fiyiano (Fiyi)
            45.	 FKP - Libra malvinense (Islas Malvinas)
            46.	 FOK - Corona feroesa (Islas Feroe)
            47.	 GBP - Libra esterlina (Reino Unido)
            48.	 GEL - Lari (Georgia)
            49.	 GGP - Libra de Guernsey (Guernsey)
            50.	 GHS - Cedi ghanés (Ghana)
            51.	 GIP - Libra de Gibraltar (Gibraltar)
            52.	 GMD - Dalasi (Gambia)
            53.	 GNF - Franco guineano (Guinea)
            54.	 GTQ - Quetzal (Guatemala)
            55.	 GYD - Dólar guyanés (Guyana)
            56.	 HKD - Dólar de Hong Kong (Hong Kong)
            57.	 HNL - Lempira (Honduras)
            58.	 HRK - Kuna (Croacia)
            59.	 HTG - Gourde (Haití)
            60.	 HUF - Florín húngaro (Hungría)
            61.	 IDR - Rupia indonesia (Indonesia)
            62.	 ILS - Nuevo shéquel (Israel)
            63.	 IMP - Libra de la Isla de Man (Isla de Man)
            64.	 INR - Rupia india (India)
            65.	 IQD - Dinar iraquí (Irak)
            66.	 IRR - Rial iraní (Irán)
            67.	 ISK - Corona islandesa (Islandia)
            68.	 JEP - Libra de Jersey (Jersey)
            69.	 JMD - Dólar jamaicano (Jamaica)
            70.	 JOD - Dinar jordano (Jordania)
            71.	 JPY - Yen (Japón)
            72.	 KES - Chelín keniano (Kenia)
            73.	 KGS - Som kirguís (Kirguistán)
            74.	 KHR - Riel camboyano (Camboya)
            75.	 KID - Dólar de Kiribati (Kiribati)
            76.	 KMF - Franco comorense (Comoras)
            77.	 KRW - Won surcoreano (Corea del Sur)
            78.	 KWD - Dinar kuwaití (Kuwait)
            79.	 KYD - Dólar de las Islas Caimán (Islas Caimán)
            80.	 KZT - Tenge kazajo (Kazajistán)
            81.	 LAK - Kip (Laos)
            82.	 LBP - Libra libanesa (Líbano)
            83.	 LKR - Rupia de Sri Lanka (Sri Lanka)
            84.	 LRD - Dólar liberiano (Liberia)
            85.	 LSL - Loti (Lesoto)
            86.	 LYD - Dinar libio (Libia)
            87.	 MAD - Dírham marroquí (Marruecos)
            88.	 MDL - Leu moldavo (Moldavia)
            89.	 MGA - Ariary malgache (Madagascar)
            90.	 MKD - Denar (Macedonia del Norte)
            91.	 MMK - Kyat (Myanmar)
            92.	 MNT - Tugrik (Mongolia)
            93.	 MOP - Pataca (Macao)
            94.	 MRU - Ouguiya (Mauritania)
            95.	 MUR - Rupia de Mauricio (Mauricio)
            96.	 MVR - Rufiyaa (Maldivas)
            97.	 MWK - Kwacha de Malaui (Malaui)
            98.	 MXN - Peso mexicano (México)
            99.	 MYR - Ringgit malayo (Malasia)
            100. MZN - Metical mozambiqueño (Mozambique)
            101. NAD - Dólar namibio (Namibia)
            102. NGN - Naira (Nigeria)
            103. NIO - Córdoba nicaragüense (Nicaragua)
            104. NOK - Corona noruega (Noruega)
            105. NPR - Rupia nepalesa (Nepal)
            106. NZD - Dólar neozelandés (Nueva Zelanda)
            107. OMR - Rial omaní (Omán)
            108. PAB - Balboa (Panamá)
            109. PEN - Sol (Perú)
            110. PGK - Kina (Papúa Nueva Guinea)
            111. PHP - Peso filipino (Filipinas)
            112. PKR - Rupia pakistaní (Pakistán)
            113. PLN - Zloty (Polonia)
            114. PYG - Guaraní (Paraguay)
            115. QAR - Rial catarí (Catar)
            116. RON - Leu rumano (Rumania)
            117. RSD - Dinar serbio (Serbia)
            118. RUB - Rublo ruso (Rusia)
            119. RWF - Franco ruandés (Ruanda)
            120. SAR - Riyal saudí (Arabia Saudita)
            121. SBD - Dólar de las Islas Salomón (Islas Salomón)
            122. SCR - Rupia de Seychelles (Seychelles)
            123. SDG - Libra sudanesa (Sudán)
            124. SEK - Corona sueca (Suecia)
            125. SGD - Dólar de Singapur (Singapur)
            126. SHP - Libra de Santa Helena (Santa Helena)
            127. SLE - Leone (Sierra Leona)
            128. SLL - Leone (Sierra Leona)
            129. SOS - Chelín somalí (Somalia)
            130. SRD - Dólar surinamés (Surinam)
            131. SSP - Libra sursudanesa (Sudán del Sur)
            132. STN - Dobra (Santo Tomé y Príncipe)
            """;

    String menu = """
            ------ MENU -------
            1. Ver el listado de monedas completos
            2. Establecer la moneda base a convertir
            3. Establecer la moneda a la que desea convertir
            4. Realizar el cálculo de conversión
            5. Salir
            """;
    }
}